import {GraySpider} from "../classes/enemies/fc/spider_gray";
import {Roller} from "../classes/enemies/fc/roller";
import {Spider} from "../classes/enemies/fc/spider";
import {Snail} from "../classes/enemies/fc/snail";
import {SpikySnail} from "../classes/enemies/fc/snail_spiky";
import {Star} from "../classes/enemies/fc/star";
import {Eel} from "../classes/enemies/fc/eel";
import {DarkEel} from "../classes/enemies/fc/eel_dark";
import {PoisonEel} from "../classes/enemies/fc/eel_poison";
import {SmallMushroom} from "../classes/enemies/fc/mushroom_small";
import {KingFrog} from "../classes/enemies/fc/frog_king";
import {Frog} from "../classes/enemies/fc/frog";
import {Cocoon} from "../classes/enemies/fc/cocoon";
import {ParanoidEel} from "../classes/enemies/bosses/paranoid_eel";
import {GuardianOfTheLight} from "../classes/enemies/bosses/guardian_of_the_light";
import {Alligator} from "../classes/enemies/dt/alligator";
import {Rabbit} from "../classes/enemies/dt/rabbit";
import {RedSpider} from "../classes/enemies/dt/spider_red";
import {GreenSpider} from "../classes/enemies/dt/spider_green";
import {FireFrog} from "../classes/enemies/dt/frog_fire";
import {KingFireFrog} from "../classes/enemies/dt/frog_king_fire";
import {LizardWarrior} from "../classes/enemies/ru/lizard_warrior";
import {MudMage} from "../classes/enemies/ru/mud_mage";
import {TeleportMage} from "../classes/enemies/ru/teleport_mage";
import {WallSlime} from "../classes/enemies/ru/wall_slime";
import {Mushroom} from "../classes/enemies/fc/mushroom";
import {SpiderSmall} from "../classes/enemies/fc/spider_small";
import {FireSnail} from "../classes/enemies/dt/fire_snail";
import {ExplosivePixie} from "../classes/enemies/dt/explosive_pixie";
import {HexEye} from "../classes/enemies/ru/hex_eye";
import {BladeDemon} from "../classes/enemies/ru/blade_demon";
import {LavaSlime} from "../classes/enemies/ru/lava_slime";
import {LunaticLeader} from "../classes/enemies/bosses/lunatic_leader";
import {LostMage} from "../classes/enemies/dt/lost_mage";
import {DeadStar} from "../classes/enemies/dc/dead_star";
import {DrySnail} from "../classes/enemies/dc/dry_snail";
import {DryCocoon} from "../classes/enemies/dc/dry_cocoon";
import {DryStar} from "../classes/enemies/dc/dry_star";
import {BombSkull} from "../classes/enemies/dc/bomb_skull";
import {DryFrog} from "../classes/enemies/dc/dry_frog";
import {DesertWorm} from "../classes/enemies/dc/desert_worm";

export const FCEnemySets = [
    [GraySpider, GraySpider, SpiderSmall],
    [Roller],
    [Spider],
    [GraySpider],
    [Snail],
    [SpikySnail],
    [Roller, Roller, Roller, Roller, Roller, Roller],
    [Star, Star, Star, Star],
    [Star, GraySpider],
    [Snail, Snail],
    [Snail, Snail, Snail],
    [Eel, Eel],
    [DarkEel],
    [PoisonEel],
    [SmallMushroom],
    [Eel],
    [SmallMushroom, SmallMushroom],
    [SmallMushroom, KingFrog],
    [KingFrog, KingFrog],
    [SmallMushroom, SmallMushroom, SmallMushroom, SmallMushroom, KingFrog],
    [Frog, Frog, Frog, Frog],
    [Frog, Frog],
    [Frog, Roller, Roller],
    [DarkEel, Snail],
    [DarkEel, Snail, Snail],
    [Spider, GraySpider, SmallMushroom],
    [Frog, SmallMushroom],
    [Frog, Eel, DarkEel],
    [PoisonEel, PoisonEel],
    [Star, PoisonEel, Star, PoisonEel],
    [Eel, Roller, Eel, Roller],
    [SpikySnail, Snail, SpikySnail, Snail],
    [SpikySnail, Spider, GraySpider],
    [SmallMushroom, Eel],
    [KingFrog],
    [KingFrog, PoisonEel],
    [KingFrog, Frog, Frog],
    [Eel, DarkEel, PoisonEel],
    [Eel, Spider],
    [Eel, Spider, Snail],
    [GraySpider, Snail],
    [GraySpider, Eel, Eel],
    [Spider, GraySpider],
    [Spider, Roller, Roller],
    [Spider, DarkEel],
    [Spider, DarkEel, DarkEel],
    [Spider, Snail],
    [GraySpider, SpikySnail],
    [Spider, SpikySnail],
    [GraySpider, SpiderSmall, Snail, Snail, Snail],
    [Eel, Eel, Eel, Eel, Eel],
    [Eel, Eel, Eel, Eel, Eel, Eel],
    [Eel, Eel, Eel, DarkEel, DarkEel, PoisonEel],
    [Eel, Frog, Snail],
    [Frog, Frog, Star, Star],
    [GraySpider, SpiderSmall, Snail, Snail],
    [Cocoon, Cocoon, Cocoon],
    [Cocoon],
    [Cocoon, Spider],
    [Cocoon, GraySpider],
    [Cocoon, GraySpider, Spider],
    [Cocoon, Cocoon, GraySpider, Spider],
    [Cocoon, Cocoon, Roller, GraySpider, Spider],
    [Cocoon, Snail, Snail, Cocoon],
    [Cocoon, Star, Star],
    [Cocoon],
    [Cocoon, Cocoon, Star],
    [Cocoon, Frog],
    [Cocoon, Cocoon, Eel, Eel],
    [Cocoon, DarkEel, Eel, Eel, Cocoon],
    [PoisonEel, Cocoon],
    [Roller, Roller, Roller, Roller, Spider],
    [Roller, Roller, Roller, Roller, Roller, Spider],
    [Roller, Roller, Roller, Roller, Roller, Star],
    [Roller, Roller, Roller, Roller, Roller, Frog],
    [Roller, Roller, Roller, Roller, Roller, Cocoon],
    [Mushroom],
    [SmallMushroom, Mushroom],
    [SmallMushroom, SmallMushroom, Mushroom],
    [SmallMushroom, SmallMushroom, Mushroom, Mushroom],
    [Roller, Mushroom, Roller],
    [Star, Mushroom, Star, Mushroom],
    [Mushroom, Mushroom],
    [Frog, Mushroom, KingFrog],
    [Eel, Mushroom, Eel],
    [Roller, Roller, Roller, Mushroom, Mushroom],
    [Cocoon, Mushroom, Mushroom],
    [Mushroom, Spider, Mushroom],
    [Mushroom, GraySpider, GraySpider],
    [Mushroom, Snail],
    [Mushroom, DarkEel, DarkEel],
    [Frog, Mushroom],
    [KingFrog, Mushroom],
    [Mushroom, SpikySnail, Snail],
    [SpiderSmall],
    [SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, SpiderSmall, SpiderSmall],
    [Cocoon, SpiderSmall],
    [Cocoon, SpiderSmall, SpiderSmall, SpiderSmall],
    [Cocoon, Cocoon, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, Snail, Snail],
    [SpiderSmall, Snail],
    [SpiderSmall, Spider],
    [SpiderSmall, Star, Star],
    [Roller, Roller, Roller, Roller, SpiderSmall, SpiderSmall],
    [GraySpider, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, SpikySnail]
];

//boss comes first!
export const FCBossSets = [
    [ParanoidEel, Eel, Eel, Eel, Eel],
    [ParanoidEel, DarkEel, DarkEel],
    [ParanoidEel, PoisonEel]
];

export const DTEnemySets = [
    [Alligator, Alligator, Alligator, Alligator, Alligator],
    [Alligator, Alligator, Alligator, Alligator],
    [Alligator, Alligator, Alligator],
    [Alligator, Alligator],
    [Alligator],
    [Rabbit],
    [Rabbit, Rabbit],
    [Rabbit, Rabbit, Rabbit],
    [Rabbit, Rabbit, Rabbit, Rabbit],
    [RedSpider],
    [RedSpider, Rabbit],
    [RedSpider, Rabbit, Rabbit],
    [GreenSpider],
    [GreenSpider, Rabbit],
    [GreenSpider, Rabbit, Alligator],
    [Cocoon],
    [Cocoon, Rabbit],
    [Cocoon, Alligator],
    [Rabbit, Alligator, Alligator, Rabbit],
    [Rabbit, Rabbit, Alligator],
    [FireFrog],
    [KingFireFrog],
    [KingFireFrog, FireFrog],
    [RedSpider, FireFrog],
    [GreenSpider, FireFrog],
    [FireFrog, FireFrog, FireFrog, Rabbit],
    [FireFrog, FireFrog, FireFrog],
    [KingFireFrog, KingFireFrog],
    [KingFireFrog, FireFrog, FireFrog],
    [KingFireFrog, Alligator],
    [Cocoon, KingFireFrog],
    [Cocoon, FireFrog],
    [Cocoon, FireFrog, FireFrog],
    [FireFrog, Alligator, Alligator],
    [GreenSpider, KingFireFrog],
    [GreenSpider, Rabbit, Rabbit, Rabbit],
    [RedSpider, Rabbit, Rabbit, Rabbit],
    [FireSnail],
    [ExplosivePixie],
    [FireSnail, FireSnail],
    [ExplosivePixie, ExplosivePixie],
    [ExplosivePixie, ExplosivePixie, ExplosivePixie],
    [ExplosivePixie, FireFrog, FireFrog],
    [ExplosivePixie, Rabbit, ExplosivePixie],
    [FireSnail, ExplosivePixie],
    [FireSnail, FireFrog, FireFrog],
    [FireSnail, KingFireFrog],
    [ExplosivePixie, Alligator, Alligator],
    [FireSnail, Alligator],
    [FireSnail, Cocoon],
    [ExplosivePixie, Cocoon],
    [FireSnail, FireSnail, FireSnail, ExplosivePixie, ExplosivePixie],
    [FireSnail, FireSnail, FireSnail],
    [ExplosivePixie, FireFrog, FireFrog, FireFrog, ExplosivePixie],
    [Cocoon, FireSnail, FireSnail],
    [FireSnail, FireSnail, Rabbit, Rabbit, Rabbit],
    [Cocoon, ExplosivePixie, Rabbit],
    [GreenSpider, ExplosivePixie],
    [GreenSpider, FireSnail],
    [RedSpider, FireSnail],
    [RedSpider, FireFrog, FireFrog],
    [ExplosivePixie, ExplosivePixie, Alligator, Alligator],
    [ExplosivePixie, Alligator, Alligator, Alligator, FireSnail],
    [ExplosivePixie, Alligator, Alligator, Alligator, Alligator],
    [FireSnail, Alligator, Alligator, Alligator, Alligator],
    [FireSnail, Alligator, Alligator],
    [ExplosivePixie, Alligator],
    [LostMage],
    [LostMage, LostMage],
    [LostMage, LostMage, LostMage],
    [LostMage, LostMage, LostMage, LostMage],
    [LostMage, ExplosivePixie],
    [LostMage, Rabbit],
    [LostMage, Rabbit, Rabbit],
    [LostMage, Rabbit, Rabbit, Rabbit],
    [LostMage, Alligator],
    [LostMage, FireSnail],
    [LostMage, FireSnail, Rabbit],
    [LostMage, Alligator, Rabbit],
    [LostMage, FireFrog],
    [LostMage, LostMage, FireFrog],
    [LostMage, KingFireFrog],
    [LostMage, Cocoon],
    [LostMage, LostMage, Rabbit, Rabbit, Rabbit],
    [LostMage, LostMage, LostMage, Rabbit, Rabbit],
    [LostMage, LostMage, ExplosivePixie, ExplosivePixie]
];

export const DTBossSets = [
    [GuardianOfTheLight]
];

export const RUEnemySets = [
    [LavaSlime],
    [BladeDemon],
    [HexEye],
    [LizardWarrior],
    [MudMage],
    [TeleportMage],
    [WallSlime],
    [LizardWarrior, LizardWarrior],
    [MudMage, WallSlime],
    [WallSlime, TeleportMage],
    [TeleportMage, MudMage],
    [LizardWarrior, TeleportMage],
    [LizardWarrior, MudMage],
    [LizardWarrior, LizardWarrior, MudMage, TeleportMage],
    [LizardWarrior, LizardWarrior, MudMage],
    [LizardWarrior, LizardWarrior, TeleportMage],
    [LizardWarrior, LizardWarrior, WallSlime],
    [WallSlime, WallSlime],
    [WallSlime, WallSlime, WallSlime],
    [LavaSlime, LavaSlime],
    [LavaSlime, LavaSlime, HexEye],
    [LavaSlime, LavaSlime, MudMage, MudMage],
    [LavaSlime, LavaSlime, LavaSlime, HexEye],
    [HexEye, HexEye],
    [HexEye, LavaSlime],
    [WallSlime, LavaSlime],
    [BladeDemon, LizardWarrior],
    [BladeDemon, BladeDemon],
    [BladeDemon, BladeDemon, BladeDemon],
    [HexEye, MudMage],
    [BladeDemon, HexEye],
    [HexEye, WallSlime, WallSlime, HexEye],
    [HexEye, WallSlime, WallSlime],
    [HexEye, HexEye, HexEye],
    [HexEye, HexEye, MudMage],
    [BladeDemon, WallSlime, LavaSlime, BladeDemon],
    [LavaSlime, LizardWarrior],
    [LavaSlime, MudMage],
    [TeleportMage, LavaSlime],
    [TeleportMage, WallSlime, WallSlime],
    [HexEye, LizardWarrior],
    [LizardWarrior, WallSlime],
    [BladeDemon, LavaSlime],
    [BladeDemon, WallSlime],
    [BladeDemon, BladeDemon, WallSlime],
    [BladeDemon, BladeDemon, WallSlime, WallSlime],
    [MudMage, BladeDemon],
    [TeleportMage, HexEye]
];

export const RUBossSets = [
    [LunaticLeader]
];

// most of them are copied from FC
// Resprites:
// Snail is replaced with DrySnail, Star is replaced with DryStar, Cocoon is replaced with DryCocoon, Frogs are replaced with Dry Frogs
// Replacements:
// Rollers are replaced with BombSkulls, SpikySnail is replaced with FireSnail,
// Added enemies:
// FireFrog, DeadStar, DesertWorm
// Removed enemies:
// Eels, Dark Eels, Poison Eels, KingFrogs and MiniStars
export const DCEnemySets = [
    [GraySpider, GraySpider, SpiderSmall],
    [BombSkull],
    [Spider],
    [GraySpider],
    [DrySnail],
    [FireSnail],
    [BombSkull, BombSkull, BombSkull, BombSkull, BombSkull, BombSkull],
    [DryStar, DryStar, DryStar, DryStar],
    [DryStar, GraySpider],
    [DrySnail, DrySnail],
    [DrySnail, DrySnail, DrySnail],
    [SmallMushroom],
    [SmallMushroom, SmallMushroom],
    [SmallMushroom, FireFrog],
    [FireFrog, FireFrog],
    [SmallMushroom, SmallMushroom, SmallMushroom, SmallMushroom, Frog],
    [DryFrog, DryFrog, DryFrog, DryFrog],
    [DryFrog, DryFrog],
    [DryFrog, BombSkull, BombSkull],
    [Spider, DeadStar],
    [DeadStar],
    [Spider, GraySpider, SmallMushroom],
    [DryFrog, SmallMushroom],
    [FireSnail, DrySnail, FireSnail, DrySnail],
    [FireSnail, Spider, GraySpider],
    [FireFrog],
    [FireFrog, DryFrog, DryFrog],
    [GraySpider, DrySnail],
    [Spider, GraySpider],
    [Spider, BombSkull, BombSkull],
    [Spider, DrySnail],
    [GraySpider, FireSnail],
    [Spider, FireSnail],
    [GraySpider, SpiderSmall, DrySnail, DrySnail, DrySnail],
    [DryFrog, DryFrog, DryStar, DryStar],
    [GraySpider, SpiderSmall, DrySnail, DrySnail],
    [DryCocoon, DryCocoon, DryCocoon],
    [DryCocoon],
    [DryCocoon, Spider],
    [DryCocoon, GraySpider],
    [DryCocoon, GraySpider, Spider],
    [DryCocoon, DryCocoon, GraySpider, Spider],
    [DryCocoon, DryCocoon, BombSkull, GraySpider, Spider],
    [DryCocoon, DrySnail, DrySnail, DryCocoon],
    [DryCocoon, DryStar, DryStar],
    [DryCocoon],
    [DryCocoon, DryCocoon, DryStar],
    [DryCocoon, DryFrog],
    [BombSkull, BombSkull, BombSkull, BombSkull, Spider],
    [BombSkull, BombSkull, BombSkull, BombSkull, BombSkull, Spider],
    [BombSkull, BombSkull, BombSkull, BombSkull, BombSkull, DryStar],
    [BombSkull, BombSkull, BombSkull, BombSkull, BombSkull, DryFrog],
    [BombSkull, BombSkull, BombSkull, BombSkull, BombSkull, DryCocoon],
    [DeadStar, DryStar],
    [DeadStar, BombSkull, BombSkull, BombSkull, BombSkull],
    [DeadStar, BombSkull, BombSkull],
    [Mushroom],
    [SmallMushroom, Mushroom],
    [SmallMushroom, SmallMushroom, Mushroom],
    [SmallMushroom, SmallMushroom, Mushroom, Mushroom],
    [BombSkull, Mushroom, BombSkull],
    [DryStar, Mushroom, DryStar, Mushroom],
    [Mushroom, Mushroom],
    [DryFrog, Mushroom, FireFrog],
    [BombSkull, BombSkull, BombSkull, Mushroom, Mushroom],
    [DryCocoon, Mushroom, Mushroom],
    [Mushroom, Spider, Mushroom],
    [Mushroom, GraySpider, GraySpider],
    [Mushroom, DrySnail],
    [Mushroom, DeadStar],
    [DryFrog, Mushroom],
    [FireFrog, Mushroom],
    [Mushroom, FireSnail, DrySnail],
    [SpiderSmall],
    [SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, SpiderSmall, SpiderSmall],
    [DryCocoon, SpiderSmall],
    [DryCocoon, SpiderSmall, SpiderSmall, SpiderSmall],
    [DryCocoon, DryCocoon, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, DrySnail, DrySnail],
    [SpiderSmall, DrySnail],
    [SpiderSmall, Spider],
    [SpiderSmall, DryStar, DryStar],
    [BombSkull, BombSkull, BombSkull, BombSkull, SpiderSmall, SpiderSmall],
    [GraySpider, SpiderSmall, SpiderSmall],
    [SpiderSmall, SpiderSmall, FireSnail],
    [FireSnail, DrySnail],
    [FireSnail, SpiderSmall],
    [FireFrog, DryFrog],
    [FireFrog, DryFrog, DryFrog, FireFrog],
    [FireFrog, FireFrog, DryFrog],
    [DesertWorm],
    [DesertWorm, DesertWorm],
    [DesertWorm, DesertWorm, DesertWorm],
    [DesertWorm, DesertWorm, DesertWorm, DesertWorm],
    [DesertWorm, BombSkull],
    [DesertWorm, DesertWorm, BombSkull, BombSkull],
    [DesertWorm, BombSkull, BombSkull],
    [DesertWorm, DesertWorm, BombSkull],
    [DesertWorm, DesertWorm, DrySnail],
    [DesertWorm, DrySnail, DrySnail],
    [DesertWorm, DryFrog, FireFrog],
    [DesertWorm, DesertWorm, FireFrog, DryFrog, SpiderSmall],
    [DesertWorm, DryStar],
    [DesertWorm, DryStar, DryStar],
    [DesertWorm, DesertWorm, DryStar, DryStar],
    [DesertWorm, DesertWorm, DesertWorm, BombSkull, SpiderSmall, SpiderSmall],
    [DesertWorm, DesertWorm, DesertWorm, BombSkull, SpiderSmall, BombSkull],
    [DesertWorm, DesertWorm, DryCocoon],
    [DesertWorm, DeadStar],
    [DeadStar, DeadStar],
    [DeadStar, DryFrog],
    [DeadStar, FireFrog],
    [DeadStar, DryFrog, FireFrog]
];

export const DCBossSets = [
    [ParanoidEel]
];